# BDD-NET therapist manual

## What is BDD-NET?
*Detailed review of the content of the product. What therapeutic interventions are included and how are they implemented?*

BDD-NET consists of eight interactive modules and is based on a treatment protocol by Sabine Wilhelm and colleagues [@wilhelm2013] that focuses on exposure with response prevention. This means that patients do most of the active treatment work away from their computer or mobile device, for example when they are performing exposure and response prevention exercises.

### Comparison between BDD-NET content and current IAPT services content in the treatment of BDD

#### Wilhelm [@wilhelm2013]
Core treatment elements:
* Psychoeducation
* Cognitive interventions (maladaptive beliefs, importance of appearance or self-worth)
* Exposure to avoided situations and prevention of rituals
* Mindfulness and perceptual retraining (e.g., to reduce selective attention to details such as appearance flaws)
* Relapse prevention

Optional treatment modules:
* Skin picking
* Surgery seeking

#### Veale [@veale2010]
* Imagery rescripting
* Modifying attentional biases
* Modifying cognitive processes
* Avoidance, compulsive, and safety behaviours
* Modifying appraisals
* Behavioural experiments to test beliefs about processes such as ruminating or mirror-gazing
* Self-monitoring and habit reversal for skin-picking


## Who is suitable for BDD-NET
*The clinical condition that the digital product has been developed for and the recommended range of symptom severities for patients using the digital product.*

BDD-NET is developed to treat adults with body dysmorphic disorder (BDD). Patients may have comorbid conditions, for example other anxiety disorders, depression, or OCD. Patients may also take antidepressant medication during the course of treatment. We recommend that patients do not change the dose during the course of treatment. BDD-NET may also be delivered to patients with any level of BDD symptom severity.

Contraindications include having a personality disorder that might interfere with treatment (such as borderline personality disorder), psychotic symptoms, an ongoing substance abuse, or acute suicidal ideation. BDD-NET is text-based and so requires sufficient reading skills and understanding of English. We recommend that the patient is referred to face-to-face treatments if contraindications are discovered.

## Presenting BDD-NET as an option to the patient
*How to present the digital product to patients in a way that generates enthusiasm and ensures that the patient promptly starts using the product. Managing patients’ expectations of BDD-NET therapy*

### Assessing insight

Participating in internet-based treatments such as BDD-NET is voluntary, and therapists need to make sure that patients are willing to challenge their BDD in treatment. Lack of insight is common in BDD and BDD-NET is designed to work for patients that express varying degrees of insight. It is our experience that patients need to at least be willing to try out alternative behaviours during the course of treatment, even if they might still be convinced that their appearance concerns are justified at the start of treatment. 

### Managing expectations

Some patients may have expectations to be completely free from anxiety after BDD-NET, and that all that is required of them is to read and understand what is written in the treatment modules. Such expectations are discussed in module 4 (goal setting) but therapists are advised to assess whether patients are willing to challenge their BDD through exposure with response prevention and try out alternative behaviours before starting BDD-NET. If someone completely refuses to try new behaviours they are unlikely to participate in BDD-NET fully and benefit from the treatment.

### A good start in BDD-NET

Many patients with BDD find BDD-NET an interesting treatment option, particularly those who avoid many activities due to their appearance concerns. The strongest arguments in favour of ICBT treatments like BDD-NET, from a patient perspective, is that the treatment content and the therapist are accessible throughout the week, and that the treatment starts promptly after evaluation rather than after a time in waiting list.

To give patients a positive first impression of the treatment, we suggest that therapists write their first message on the first day of treatment to welcome the patient and notify them of ways to contact you. Provide encouragement throughout treatment to motivate the patient and establish a therapeutic working alliance. Patients sometimes struggle with crucial treatment components such as the BDD diary exposure with response prevention (ERP), so make sure to provide extra support if patients get stuck at those points.

## Modules in BDD-NET

Below is an overview of the eight treatment modules. We recommend that you look at them from a patient's point of view before starting the first treatment.

| **Treatment module** | **Content** |
| :--- | :--- |
| 1. Introduction to BDD and the treatment | An introduction to BDD <br> Introduction to the treatment content |
| 2. A CBT model of BDD | Psychological explanation of the link between thoughts, emotions, and behaviours  |
| 3. Interpretation traps | Common cognitive biases in BDD |
| 4. Introduction to ERP | Goal setting and planning of exposure with response prevention |
| 5. More about ERP | Doing and evaluating exposure with response prevention exercises |
| 6. Values and Goals | Identifying and acting in accordance with personal values |
| 7. Difficulties during treatment | Strategies to deal with common difficulties and setbacks |
| 8. Summary and Relapse Prevention | Treatment summary, evaluation of treatment, and designing a relapse prevention plan |

As you can see, the emphasis is on doing exposure with response prevention (ERP), which we view as the main component of BDD-NET. You typically want to encourage the patient to progress through the first three modules as fast as possible, check that they have understood the rationale for ERP, and then start doing ERP. Once a patient is doing regular ERP-exercises, you can open up modules 6-7 for them to complete while continuing to do daily ERP. Module 8 can then be opened up with one to two weeks left in treatment.

## Closing remarks
...

We strive to continuously update and improve this material and would appreciate any feedback. You can reach us at <ocdnet.support@webcbt.se> or talk to us in person at a training session.