# Being an effective ICBT therapist

Being a therapist in internet-based CBT (ICBT) differs in several ways from regular face-to-face treatment. The first difference is the mode of communication: asynchronous text messages rather than live face-to-face talking. The second is that therapists are more closely integrated in the treatment content, and will rely more heavily on the written material. Third, there is less therapist oversight during active ERP exercises. We will discuss these implications below.

## Support messages

Therapists should write to patients on their first day in treatment, introduce themselves (if they have not been in contact before) and present the treatment. For example, therapists can give instructions for how to navigate the platform, how much time the patient should spend on the first module, and how to contact mental health services in case of an emergency.

<details>
<summary> Click to read an example of the first message sent to a patient </summary>

*Welcome to the treatment!*

*My name is Oskar and I will be your therapist during the 12 weeks that you are in treatment. You can write messages to me whenever you have questions or want to discuss the treatment content. I check the platform every day and will respond as quickly as I can.*

*The treatment is structured as modules, and each module contains homework exercises as well as worksheets. Once you have read a module and completed the homework, it is sent to me and I will give you feedback. As you can see, module 1 is already opened and I look forward to your comments!*

*Again, don't hesitate to contact me if you have any questions.*

*Best, Oskar*

</details>

We recommend that therapists check and respond to messages at least once per day. Patients in the studies on BDD-NET and OCD-NET have all received responses within 24 hours on weekdays. We believe that the frequent feedback from a therapist is important to keep patients engaged in the therapy throughout treatment.

The most common questions that patients pose in ICBT relate to understanding and applying the treatment material, clarifying the therapeutic process, and addressing technical challenges [@soucy2019].

### Keep your messages short

Messages should be concise and to the point but still using a personal touch. The main aim is to provide encouragement and reinforce key behaviours in the treatment, such as registrations in the OCD/BDD diary and performing ERP exercises.

There are some exceptions to this rule. Therapists are advised to write longer messages when needed: to highlight examples in the diary that are informative and relate these to the CBT model of OCD/BDD, or to provide encouragement by linking ERP exercises to a patient's long-term goals and values.

### Write often

Frequent communication is particularly useful at the start of treatment and when patients are in the startup phase of ERP. In many ways, ICBT may be an even more intensive treatment than traditional face-to-face CBT for patients. Our standard procedure is to contact patients at least twice weekly, but more often when needed. For example, therapists may confirm an exposure exercise in the morning and check in during the afternoon for a follow-up. 

There are exceptions to the rule of frequent messages: some patients will prefer to do ERP exercises on their own and will not have many questions. This is perfectly fine; some patients benefit greatly from the ICBT treatment without the therapist support.

### What to include in support messages

We recommend that therapists begin by summarising the content in the patient's message and validate concerns and/or struggles they may have mentioned. Therapists should then address and provide feedback on specific treatment activities (completing content on the platform or practicing skills from treatment in their daily life), with an emphasis on positive reinforcement and encouragement. An effective ending typically includes a suggestion of next steps, encouragement to continue with planned exercises, a question, or a call to action.

| **What to include in support messages** |
| :---- |
| Summarise the main points or questions of the patient's message |
| Validate concerns and/or struggles mentioned |
| Provide positive feedback and encouragement on engagement with the treatment and practice of treatment skills |
| End with a call to action, suggestion of next steps, or a question |

## Therapists and the rest of the content in ICBT

As previously mentioned, ICBT is in many ways a high intensity treatment. Patients not only respond to messages but also read module texts, answer homework questions and questionnaires, and fill in worksheets. The treatment becomes particularly intensive once patients start performing daily ERP exercises. Thus, what might feel like a low-intensity treatment from the therapist perspective is actually be very intensive for patients.

Therapists should keep in mind that patients do many other things besides writing and responding to messages. Corrective feedback is sometimes necessary in order to design, do, and evaluate effective ERP exercises. We recommend that therapists are generally restrictive about corrective feedback when it is not clearly needed for ERP, but therapists should use their clinical judgment in these situations.

## Promoting hands-on ERP exercises

With the restrictions on therapist input in ICBT, what therapists attend to in messages signal what patients are expected to work on during treatment. A typical message from a patient mid-treatment might include a summary of their latest ERP exercise, comments about what they have found challenging, and a couple of questions about the treatment content. It is very tempting to try to answer the questions and make suggestions for how to deal with the challenges in the response, but that could shift attention away from doing ERP exercises. Rather, we want to encourage the patient to continue doing ERP because that is the key behaviour for them to get better in the long-term.

Therapists should therefore strive to balance feedback to aid understanding with actionable advice that patients can put into practice. For example, a lack of clarity in an ERP exercise or choosing the wrong ERP exercise could result in the patient getting stuck and asking questions. A therapist could then address both the uncertainties and promote behaviour change through ERP by suggesting a variation of the ERP exercise or suggesting a new one that is better suited for the situation. This is likely to be a more effective strategy compared to just addressing the questions one by one without linking them to ERP exercises or behaviour change.

### Lack of therapist-guided exposure exercises

We do not have the privilege of guiding patients through ERP exercises in ICBT. This means that therapists will have to focus on the essentials when giving corrective feedback to patients. Correcting every little detail before each exercise will in this context probably be counter-productive and might in fact confuse the patient. Instead, our focus is to get patients going with the ERP exercises. Wrinkles can be ironed out along the way.

## Reinforcing progress

Therapists are advised to provide lots of encouragement when patients complete core activities in ICBT such as the OCD/BDD diary and performing ERP exercises. It is helpful to clarify how these activities contribute to the patient's long-term goals, to repeat main takeaways from the modules, and to communicate in a personal tone in order to avoid rigid responses. For example, we often give personal examples of intrusive thoughts (preferably bizarre ones) in order to normalise that having unwanted thoughts is not dangerous.

<details>
<summary> Click to read an example of a therapist response that reinforces progress </summary>

Hi! It's great to see that you work through the material so quickly and are eager to get started with exercises!

You have done a thorough job on this module about interpretations. It's clear to me that you have embraced the CBT-perspective on thoughts: it is not the thoughts themselves but how we *interpret* those thoughts that matters. The problems occur when we respond with compulsions and other behaviours in response to the intrusive thoughts, which reinforces the thoughts.

In this treatment, we will not try to change the thoughts themselves, for example by trying to disprove them. Obsessive thoughts resist logic and will not disappear just by arguing with yourself. Rather, the goal is for you to gain new experiences by responding differently to the obsessive thoughts.

Great work on module 3, I have granted access to module 4. Good luck and please reach out if you have any questions!

</details>

<details>
<summary> Click to read an example of a therapist encouraging a patient to accept their obsessive thoughts </summary>

Hi X! Trying to avoid or fight your obsessional thoughts usually backfires. These strategies intensify the obsessions and keep you convinced that these thoughts are more harmful, dangerous, and important than they really are. You become stuck in a vicious cycle.

My suggestion is that you try to accept your obsessive thoughts. Strive to accept the thought "what if I flirted with that person?" and accept the possibility that you might have flirted. Don't try to debate or argue with your obsessive thoughts. By accepting the thought, you might conclude that "yes, I might have flirted with several people, I have to accept that possibility."

This is not an easy thing to do, and our automatic response is usually to argue with our thoughts. But if you constantly try to argue or debate with your obsessive thoughts–or in any other way try to make them go away–they will find a way back sooner or later. Try to let your obsessive thoughts exist along every other thought and accept that they occur from time to time. What do you think?

</details>

## Dealing with patients who struggle in treatment

This list of struggles in ICBT is based on our clinical experience of developing and working with ICBT for OCD and BDD. We will update the list when we become aware of other common struggles, so please discuss difficult cases with your colleagues and in supervision. If you want to make us aware of a common struggle not listed below, send an email to <ocdnet.support@webcbt.se>.

### Patients who ask many questions

Asking questions to receive reassurance is a common strategy for anxiety reduction in both BDD and OCD. Therapists should therefore expect more frequent questions from patients when anxiety levels are likely to be high: in the beginning of treatment (when they learn more about their OCD/BDD), and when they are about to start ERP exercises. For example, it is common for patients to ask whether their OCD/BDD beliefs are realistic or not, and whether a particular ERP exercise is safe to do. When this is the case, we recommend that therapists validate the anxiety patients feel when they challenge their OCD/BDD, but that they refrain from providing reassurance.

<details>
<summary> Click to read an example of a therapist writing about his own bizarre thoughts </summary>

Hi X! It's impossible to *not* think certain thoughts. You will always have intrusive sexual thoughts about people close to you. It's part of being human and I want to remind you to accept that you have those thoughts from time to time. As soon as you try to argue with your thoughts or try to analyse them you will be trapped and the thoughts will be disturbing.

Every morning when I change my daughter's diapers, I get an intrusive thought that I will sexually abuse her. I can't avoid thinking these thoughts, and I know that if I start to argue with them or try to make them go away, they will return and become more disturbing. So instead I accept them and let them exist among my other, more neutral or positive, thoughts. This is what I want you to try from now on!

You have done a great job on the exposures these past days and I think that the content in module 9 will be helpful for you.

Best regards,
X

</details>

Other times, there is genuine confusion about the point of a particular ERP exercise or the content in a module (most common in the modules about interpretations). When this is the case, make sure that the patient has learned key skills and takeaways needed for ERP: understanding the CBT model and the role of safety behaviours/compulsions in maintaining the disorder, the rationale for ERP, having specific and measurable goals, and having a plan for ERP exercises. Once these foundations are in place, therapists should encourage patients to get started with ERP and adapt exercises as they go along.

<details>
<summary> Click to view an example of a therapist explaining the rationale for imaginal exposure </summary>

Imaginal exposures are a bit special, the point is not for you to *not* have an emotional reaction to the thoughts. These aggressive thoughts are unpleasant for anyone, and it is likely that you will always experience the thought as repugnant. Rather, the point is for you to practice to let the thought exist without acting on it. By working on imaginal exposures, you accept that you will have unpleasant thoughts from time to time and that you don't need to act on them. The point, then, is that the thought is unpleasant but you can let it exist anyway. We are not able to control our thoughts and trying to do so usually backfires. Imaginal exposure presents another way to relate to your unpleasant thoughts.

</details>

### Patients who struggle with ERP exercises

Behaviour change is difficult, and when patients start to challenge their OCD/BDD with ERP they are likely to experience the exercises as difficult at some point. In fact, a patient that never has any difficulties in ERP is likely not doing exercises that are challenging enough!

There are entire modules dedicated to common difficulties during treatment, and therapists can refer to the text in those modules for suggestions on how to respond when patients experience difficulties. Therapists should write the responses in their own words rather than copying text from the module.

<details>
<summary> Click to read an example of a therapist response when a patient has expressed worry about doing the right ERP exercises </summary>

Hi, excellent work so far! Having thoughts about not doing the right ERP exercises is something that most patients experience at one point or another. This is to be expected and something that your brain does when you perform ERP. You can view them as one type of obsessive thoughts that we deal with in the same way we deal with all obsessive thoughts: we let them exist and leave them alone.

(Gives a few suggestions of ERP exercises–previously listed in the exposure hierarchy–to be performed the same day.) Perhaps you could do one of these exercises today? I look forward to hearing about how it went!

</details>

### Patients with low engagement

The best way to deal with low engagement is to prevent it from happening to begin with. Strategies to prevent low engagement include:

1. Writing frequently (especially in the beginning of treatment in order to keep up momentum)
2. Focusing on encouragement in written messages
3. Promptly calling patients that do not respond to messages
4. Providing support and help to patients that struggle with ERP exercises

If a patient becomes less active on the treatment platform, it does not necessarily mean that they have stopped working with the treatment or have given up on the treatment. Some inactive patients are doing a lot of treatment work in their daily life but do not report this spontaneously to their therapist.

### Patients express lack of time to work on the treatment

One common reason for low engagement is that the patient struggles to find the time to work on ICBT. We recommend that therapists encourage any small steps the patient takes and that they prioritise ERP exercises away from the computer over reading additional modules.

If a patient is completely unable to work on the treatment right now, ask him/her if it possible to delay the start of treatment. The absolute majority of patients responding to OCD-NET and BDD-NET experience this gain within the first 5 weeks after starting treatment. Thus, even if the patient is delayed and start the treatment at week 5, it is still possible to achieve a significant improvement given that the patient works with the treatment intensively.

### Patients express skepticism about ICBT

Some patients may be skeptical about ICBT in general or in their ability to complete a remote treatment without face-to-face support from a therapist. We recommend that therapists validate and acknowledge that these concerns are common early in treatment and, importantly, help skeptical patients experience *early wins* by starting with swift and easy ERP exercises.

<details>
<summary> Click to read an example response to a patient that is ambivalent towards CBT </summary>

Hi X! I notice that you are ambivalent about doing this treatment and that you have some doubts whether CBT will really help you. First of all, I really appreciate that you are honest about this!

It is completely normal to be ambivalent early in the treatment. Most people feel that their rituals are excessive and out of control, but still worry that a disaster might happen if they stop doing them. Others might be afraid that they will be asked to do absurd things in treatment that is completely against their idea of normal behaviours. Another reason for being ambivalent is not feeling like you have enough time to devote to treatment. If one or more of these apply to you, know that others who have ended up benefitting greatly from the treatment have also been ambivalent.

Overcoming OCD/BDD is challenging, and you will have to face your fears and reduce (or stop) your rituals at some point. But it's worth it. The anxiety and fear provoked by the treatment are temporary side effects, and they don't have any long-lasting harmful consequences. If you engage with this treatment, you have a good chance of reclaiming control and freedom in your life.

My role as your therapist is to support you throughout treatment, and I want to stress that *you* are the one in the driver's seat. You decide which goals are important to reach, and you will do the work to get better. I therefore ask that you give this treatment a chance and do your best to follow the instructions, because then you will be giving yourself the best possible chances of getting over your OCD/BDD.

</details>

It is important to stress that OCD-NET and BDD-NET have never been designed as full alternatives to face-to-face CBT but should instead be seen as a complementary approach. Patients who are skeptical about ICBT from the beginning will probably not benefit from this treatment modality. Alternative formats and treatments are probably a more feasible option in these cases.

### Perceived external pressure

Some patients are pressured to come for an assessment, typically by a close relative or, in the case of BDD, sometimes by a cosmetic surgeon. Patients that are under external pressure to undergo treatment should not be selected for ICBT treatments such as OCD-NET or BDD-NET, since these treatments require self-guided exposure exercises to be effective.

### Deterioration in symptom measures

A deterioration in symptom measures can sometimes occur when patients start doing ERP exercises and is usually not an issue if symptoms are reduced in the following weeks.

If symptom levels remain high despite frequent ERP exercises, share this information with the patient and discuss what might explain this pattern. We list some common explanations below.

| Reason for increased symptoms | Proposed solution |
| :---- | :---- |
| Subtle avoidance or safety behaviours during ERP | Help the patient identify and remove these by probing mental safety behaviours: *What goes through your mind as you do ERP, are you trying to manage your anxiety in any way?* |
| Lack of habituation despite proper ERP | Suggest longer ERP exercises or variations of the same ERP exercise <br> Ask for other signs of improvement: *What have you learned from staying in the situation? <br> What new skills have you acquired from doing this ERP exercise?* |

## Ending treatment prematurely

### Due to inactivity

We recommend that patients who have been inactive for **20 days** end treatment. However, the treatment platform will create a flag after 7 days of inactivity to alert therapists. Before ending treatment, there are several steps that therapists can take to avoid long periods of inactivity.

**When the inactivity flag appears:**  

* Ensure that SMS reminders are working properly: Do you still have the correct number? Are the text messages being sent?  
* Check previous messages: Has the patient indicated in a previous message that they will be away? Do they have a plan for how to work on treatment while being away from a computer?  
* Write a message on the platform where you encourage the patient to log onto the platform and report their progress in treatment.  
* Wait 4 days.  

**4 days after inactivity flag:**  

* Make a telephone call to the patient. If no response, write a text message with information about when you will call. Then try at the indicated time.  
* Send a letter to the patient with instructions to log onto the platform. Provide information that treatment will end prematurely if the patient is inactive for 20 days.  

**After 20 days of inactivity:**  

* Check that the assessment dates are correct.  
* Write one more message to the patient where you inform that the treatment has ended and ask that they complete assessments.  
* Move the patient to "post-assessment" group.  

### Increased suicidality or self-harm

Patients who express ongoing suicidal thoughts or have ongoing self-harm behaviour should be referred to treatments with more intensive monitoring and are generally not recommended to start ICBT. However, some patients who undergo CBT for OCD and BDD express a short-term increase in suicidal ideation or self-harm behaviour while in treatment.

If this is detected either through patient-therapist messages or in weekly measurements, we recommend that therapists follow local guidelines to assess and manage risk. If a patient requires more intensive monitoring, recurring telephone assessments can be added while continuing with the treatment. In other cases, treatment will need to be ended prematurely in order to manage the increase in suicidality.

### Other reasons

A patient may request that they end treatment early for another reason than the two outlined above. Our recommendation is that therapists encourage patients to continue if they express common difficulties (e.g., struggling with the first ERP exercise or is skeptical of OCD-NET/BDD-NET prior to trying ERP for the first time). Most of these difficulties can be resolved within a week or two with increased therapist support. Seek supervision when necessary.

**If a patient asks to end treatment early, call them:**  

* What is the reason, are there any misunderstandings about the treatment that you can clarify? Are they concerned about not doing well enough in the treatment? See if you can motivate the patient to at least try a few exposure exercises.  
* Does the patient feel that the treatment does not address their main concerns? See if you can understand what type of help the patient wants and assess whether the ongoing treatment is likely to address that or not.  
* Is the patient likely to benefit from the treatment if they perform key behaviours (e.g., exposure with response prevention)? If not, it is advisable to end treatment early rather than complete the full duration.  

You may come to the conclusion that the treatment is not suitable for the patient (see a list in the OCD-NET and BDD-NET manuals), or that the patient is unlikely to benefit from OCD-NET or BDD-NET. Weekly assessments should then be de-activated on the platform, but keep the post-assessment as is. If no further action is necessary, inform the patient that they will be asked to return to the clinic for a post-assessment after the treatment period is over.
